language: php

php:
  - '7.2'
  - '7.3'

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - data/vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php data/vendor/bin/php-coveralls
