admin:
  default:
    route: '/'
    controller: 'LoxBerryPlugin\Controller\DummyController'
    method: 'GET'
    action: 'testPage'
  test:
    route: '/test'
    controller: 'LoxBerryPlugin\Controller\DummyController'
    method: 'GET,POST'
    action: 'testPage'

#public:
#  default:
#    route: '/'
#    controller: 'LoxBerryPlugin\Controller\MyPublicController'
#    method: 'GET,POST'
