admin:
  home:
    route: '/'
    controller: 'LoxBerryPlugin\Controller\DummyController'
    method: 'GET'
    action: 'testPage'
  logs:
    route: '/logs'
    controller: 'LoxBerryPlugin\Controller\DummyController'
    method: 'GET,POST'
    action: 'testPage'

#public:
#  default:
#    route: '/'
#    controller: 'LoxBerryPlugin\Controller\MyPublicController'
#    method: 'GET,POST'
