services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $packageDirectory: '%plugin.directory%'
      $packageName: '%plugin.name%'
      $cronLogger: '@logger.cron'
      $rootPath: '%runtime.root_dir%'

  _instanceof:
    LoxBerryPlugin\Core\Cron\CronJobInterface:
      tags: ['plugin.cron_job']
    LoxBerryPlugin\Core\Frontend\AbstractController:
      tags: ['plugin.controller', 'controller.service_arguments']
    Twig\Extension\AbstractExtension:
      tags: ['twig.extension']

  LoxBerryPlugin\:
    resource: '../src/*'

  LoxBerry\:
    resource: '../vendor/moay/loxberry-core/src/*'

  LoxBerryPlugin\Core\Cron\CronJobRunner:
    public: true
    arguments:
      $cronJobs: !tagged plugin.cron_job

  LoxBerryPlugin\Core\Frontend\Routing\PageRouterInterface:
    class: LoxBerryPlugin\Core\Frontend\Routing\PageRouter
    public: true

  LoxBerryPlugin\Core\Frontend\Routing\ControllerExecutor:
    arguments:
      $controllers: !tagged plugin.controller

  LoxBerry\Logging\Database\LogFileDatabase:
    factory: '@LoxBerry\Logging\Database\LogFileDatabaseFactory'

  LoxBerryPlugin\Core\Frontend\Twig\TwigEnvironmentFactory:
    arguments:
      $extensions: !tagged twig.extension

  Twig\Environment:
    class: 'Twig\Environment'
    factory: '@LoxBerryPlugin\Core\Frontend\Twig\TwigEnvironmentFactory'

  logger.cron:
    class: 'LoxBerry\Logging\Logger'
    factory: '@LoxBerryPlugin\Core\Cron\CronLoggerFactory'
