services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $packageName: '%plugin.name%'
      $cronLogger: '@logger_cron'

  _instanceof:
    LoxBerryPlugin\Core\Cron\CronJobInterface:
      tags: ['plugin.cron_job']
    LoxBerryPlugin\Core\Frontend\AbstractController:
      tags: ['plugin.controller']

  LoxBerryPlugin\:
    resource: '../src/*'

  LoxBerry\:
    resource: '../vendor/moay/loxberry-core/src/*'

  LoxBerryPlugin\Core\Cron\CronJobRunner:
    public: true
    arguments:
      $cronJobs: !tagged plugin.cron_job

  LoxBerryPlugin\Core\Frontend\Routing\PageRouter:
    public: true

  LoxBerryPlugin\Core\Frontend\Routing\ControllerExecutor:
    arguments:
      $controllers: !tagged plugin.controller

  LoxBerry\Logging\Database\LogFileDatabase:
    factory: '@LoxBerry\Logging\Database\LogFileDatabaseFactory'

  logger_cron:
    class: 'LoxBerry\Logging\Logger'
    factory: '@LoxBerryPlugin\Core\Cron\CronLoggerFactory'
